import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.scss';
import StyledComponentsRegistry from '@/lib/registry';
import VideoBg from '@/components/video-bg';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: React.PropsWithChildren) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <VideoBg />
          {props.children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
